---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  labels:
    app: whereami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: whereami
        image: gcr.io/b1-services-230040/whereami:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whereami
  labels:
    app: whereami
spec:
  selector:
    app: whereami
  ports:
  - name: http
    port: 8080
