---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  labels:
    app: whereami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: whereami
        image: gcr.io/b1-services-230040/whereami:v0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whereami
  labels:
    app: whereami
spec:
  selector:
    app: whereami
  ports:
  - name: http
    port: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: whereami
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - "apps.v3.lcl.time-keeper.watch"
  http:
  - match:
    - uri:
        prefix: "/whereami"
    route:
    - destination:
        host: whereami
        port:
          number: 8080
